"""initial schema

Revision ID: 41b344b218fa
Revises: 
Create Date: 2026-09-19 22:05:39.464463
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types (GUID, UTCDateTime) live here.
import app.core.db

revision: str = '41b344b218fa'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_admins',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_admins')),
    sa.UniqueConstraint('email', name=op.f('uq_platform_admins_email'))
    )
    op.create_table('subscription_plans',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monthly_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('max_branches', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_products', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans')),
    sa.UniqueConstraint('code', name=op.f('uq_subscription_plans_code'))
    )
    op.create_table('tenants',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('trial', 'active', 'restricted', 'suspended', name='tenantstatus', native_enum=False, length=48), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('tin', sa.String(length=64), nullable=True),
    sa.Column('business_type', sa.String(length=120), nullable=True),
    sa.Column('logo_asset_id', app.core.db.GUID(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('allow_negative_stock', sa.Boolean(), nullable=False),
    sa.Column('require_customer_for_credit', sa.Boolean(), nullable=False),
    sa.Column('hide_out_of_stock_online', sa.Boolean(), nullable=False),
    sa.Column('reminder_lead_days', sa.Integer(), nullable=False),
    sa.Column('default_tax_rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('onboarding_completed_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('last_login_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit_events',
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=True),
    sa.Column('actor_user_id', app.core.db.GUID(), nullable=True),
    sa.Column('actor_platform_admin_id', app.core.db.GUID(), nullable=True),
    sa.Column('actor_label', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', app.core.db.GUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_events_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('branches',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_branches_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_branches_tenant_code')
    )
    op.create_index(op.f('ix_branches_tenant_id'), 'branches', ['tenant_id'], unique=False)
    op.create_table('categories',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_id', app.core.db.GUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_categories_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_categories_tenant_name')
    )
    op.create_index(op.f('ix_categories_tenant_id'), 'categories', ['tenant_id'], unique=False)
    op.create_table('feature_flags',
    sa.Column('tenant_id', app.core.db.GUID(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_feature_flags_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_flags')),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_feature_flags_tenant_key')
    )
    op.create_index(op.f('ix_feature_flags_tenant_id'), 'feature_flags', ['tenant_id'], unique=False)
    op.create_table('file_assets',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_backend', sa.String(length=24), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by_id', app.core.db.GUID(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_file_assets_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_file_assets_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_assets'))
    )
    op.create_index(op.f('ix_file_assets_tenant_id'), 'file_assets', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', app.core.db.GUID(), nullable=True),
    sa.Column('kind', sa.Enum('low_stock', 'credit_reminder', 'new_enquiry', 'trial_expiry', 'import_complete', 'general', name='notificationkind', native_enum=False, length=48), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', app.core.db.GUID(), nullable=True),
    sa.Column('read_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_notifications_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index('ix_notifications_tenant_user_read', 'notifications', ['tenant_id', 'user_id', 'read_at'], unique=False)
    op.create_table('online_stores',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('telegram_username', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('show_prices', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_online_stores_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_online_stores')),
    sa.UniqueConstraint('slug', name='uq_online_stores_slug')
    )
    op.create_index(op.f('ix_online_stores_tenant_id'), 'online_stores', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_roles_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_roles_tenant_name')
    )
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.Column('plan_id', app.core.db.GUID(), nullable=True),
    sa.Column('status', sa.Enum('trialing', 'active', 'expired', 'cancelled', name='subscriptionstatus', native_enum=False, length=48), nullable=False),
    sa.Column('trial_started_on', sa.Date(), nullable=True),
    sa.Column('trial_ends_on', sa.Date(), nullable=True),
    sa.Column('current_period_ends_on', sa.Date(), nullable=True),
    sa.Column('cancelled_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name=op.f('fk_subscriptions_plan_id_subscription_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_subscriptions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('tenant_id', name=op.f('uq_subscriptions_tenant_id'))
    )
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telegram_username', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('tin', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_suppliers_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_index(op.f('ix_suppliers_tenant_id'), 'suppliers', ['tenant_id'], unique=False)
    op.create_index('ix_suppliers_tenant_name', 'suppliers', ['tenant_id', 'name'], unique=False)
    op.create_table('customers',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('telegram_username', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('credit_limit_behaviour', sa.String(length=24), nullable=True),
    sa.Column('default_branch_id', app.core.db.GUID(), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['default_branch_id'], ['branches.id'], name=op.f('fk_customers_default_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_customers_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_index('ix_customers_tenant_name', 'customers', ['tenant_id', 'name'], unique=False)
    op.create_index('ix_customers_tenant_phone', 'customers', ['tenant_id', 'phone'], unique=False)
    op.create_table('import_jobs',
    sa.Column('status', sa.Enum('uploaded', 'mapped', 'validated', 'completed', 'failed', 'cancelled', name='importjobstatus', native_enum=False, length=48), nullable=False),
    sa.Column('file_asset_id', app.core.db.GUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('column_mapping_json', sa.Text(), nullable=True),
    sa.Column('detected_headers_json', sa.Text(), nullable=True),
    sa.Column('branch_id', app.core.db.GUID(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('created_products', sa.Integer(), nullable=False),
    sa.Column('updated_products', sa.Integer(), nullable=False),
    sa.Column('skipped_rows', sa.Integer(), nullable=False),
    sa.Column('created_by_id', app.core.db.GUID(), nullable=True),
    sa.Column('completed_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_import_jobs_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_import_jobs_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_asset_id'], ['file_assets.id'], name=op.f('fk_import_jobs_file_asset_id_file_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_import_jobs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_jobs'))
    )
    op.create_index(op.f('ix_import_jobs_tenant_id'), 'import_jobs', ['tenant_id'], unique=False)
    op.create_table('products',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=24), nullable=False),
    sa.Column('category_id', app.core.db.GUID(), nullable=True),
    sa.Column('preferred_supplier_id', app.core.db.GUID(), nullable=True),
    sa.Column('image_asset_id', app.core.db.GUID(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('online_description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('track_stock', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['image_asset_id'], ['file_assets.id'], name=op.f('fk_products_image_asset_id_file_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preferred_supplier_id'], ['suppliers.id'], name=op.f('fk_products_preferred_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_products_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_is_published'), 'products', ['is_published'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_index('ix_products_tenant_name', 'products', ['tenant_id', 'name'], unique=False)
    op.create_index('uq_products_tenant_sku', 'products', ['tenant_id', 'sku'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', app.core.db.GUID(), nullable=False),
    sa.Column('permission', sa.Enum('business:view', 'business:manage', 'branch:view', 'branch:manage', 'user:view', 'user:manage', 'settings:manage', 'audit:view', 'product:view', 'product:manage', 'product:import', 'cost:view', 'pricing:manage', 'stock:view', 'stock:receive', 'stock:transfer', 'stock:adjust', 'stock:count', 'sale:view', 'sale:create', 'sale:void', 'discount:approve', 'purchase:view', 'purchase:create', 'customer:view', 'customer:manage', 'supplier:view', 'supplier:manage', 'credit:view', 'credit:create', 'credit:payment', 'credit:duedate', 'credit:cancel', 'credit:limit_override', 'credit:followup', 'shop:view', 'shop:manage', 'enquiry:view', 'enquiry:manage', 'quotation:view', 'quotation:manage', 'report:sales', 'report:profit', 'report:inventory', 'report:credit', 'report:branch_compare', name='permission', native_enum=False, length=48), nullable=False),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission', name='uq_role_permissions_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('stock_locations',
    sa.Column('branch_id', app.core.db.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('shop', 'warehouse', name='locationkind', native_enum=False, length=48), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_stock_locations_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_stock_locations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_locations'))
    )
    op.create_index(op.f('ix_stock_locations_branch_id'), 'stock_locations', ['branch_id'], unique=False)
    op.create_index(op.f('ix_stock_locations_tenant_id'), 'stock_locations', ['tenant_id'], unique=False)
    op.create_table('tenant_memberships',
    sa.Column('user_id', app.core.db.GUID(), nullable=False),
    sa.Column('role_id', app.core.db.GUID(), nullable=False),
    sa.Column('status', sa.Enum('invited', 'active', 'disabled', name='membershipstatus', native_enum=False, length=48), nullable=False),
    sa.Column('has_all_branches', sa.Boolean(), nullable=False),
    sa.Column('invited_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('invitation_token', sa.String(length=64), nullable=True),
    sa.Column('accepted_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_tenant_memberships_role_id_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_memberships_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tenant_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_memberships')),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_tenant_memberships_tenant_user')
    )
    op.create_index(op.f('ix_tenant_memberships_invitation_token'), 'tenant_memberships', ['invitation_token'], unique=False)
    op.create_index(op.f('ix_tenant_memberships_tenant_id'), 'tenant_memberships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_memberships_user_id'), 'tenant_memberships', ['user_id'], unique=False)
    op.create_table('branch_assignments',
    sa.Column('membership_id', app.core.db.GUID(), nullable=False),
    sa.Column('branch_id', app.core.db.GUID(), nullable=False),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_branch_assignments_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['tenant_memberships.id'], name=op.f('fk_branch_assignments_membership_id_tenant_memberships'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branch_assignments')),
    sa.UniqueConstraint('membership_id', 'branch_id', name='uq_branch_assignments_membership_branch')
    )
    op.create_index(op.f('ix_branch_assignments_branch_id'), 'branch_assignments', ['branch_id'], unique=False)
    op.create_index(op.f('ix_branch_assignments_membership_id'), 'branch_assignments', ['membership_id'], unique=False)
    op.create_table('customer_enquiries',
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('new', 'in_review', 'quoted', 'closed', name='enquirystatus', native_enum=False, length=48), nullable=False),
    sa.Column('customer_id', app.core.db.GUID(), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('delivery_location', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('requested_items_json', sa.Text(), nullable=True),
    sa.Column('wants_proforma', sa.Boolean(), nullable=False),
    sa.Column('handled_by_id', app.core.db.GUID(), nullable=True),
    sa.Column('handled_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_enquiries_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['handled_by_id'], ['users.id'], name=op.f('fk_customer_enquiries_handled_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_customer_enquiries_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_enquiries'))
    )
    op.create_index(op.f('ix_customer_enquiries_tenant_id'), 'customer_enquiries', ['tenant_id'], unique=False)
    op.create_index('ix_customer_enquiries_tenant_status', 'customer_enquiries', ['tenant_id', 'status'], unique=False)
    op.create_table('import_row_errors',
    sa.Column('job_id', app.core.db.GUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(length=120), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('raw_value', sa.String(length=255), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['import_jobs.id'], name=op.f('fk_import_row_errors_job_id_import_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_row_errors'))
    )
    op.create_index(op.f('ix_import_row_errors_job_id'), 'import_row_errors', ['job_id'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('scope', sa.Enum('business', 'category', 'product', name='pricingscope', native_enum=False, length=48), nullable=False),
    sa.Column('category_id', app.core.db.GUID(), nullable=True),
    sa.Column('product_id', app.core.db.GUID(), nullable=True),
    sa.Column('basis', sa.Enum('markup', 'margin', name='pricingbasis', native_enum=False, length=48), nullable=False),
    sa.Column('rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('rounding_increment', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_pricing_rules_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_pricing_rules_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_pricing_rules_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pricing_rules')),
    sa.UniqueConstraint('tenant_id', 'scope', 'category_id', 'product_id', name='uq_pricing_rules_scope_target')
    )
    op.create_index(op.f('ix_pricing_rules_tenant_id'), 'pricing_rules', ['tenant_id'], unique=False)
    op.create_index('ix_pricing_rules_tenant_scope', 'pricing_rules', ['tenant_id', 'scope'], unique=False)
    op.create_table('product_variants',
    sa.Column('product_id', app.core.db.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('attributes_json', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('transport_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('other_costs', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('average_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('max_discount_percent', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('min_stock', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('reorder_level', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_variants_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_product_variants_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants'))
    )
    op.create_index('ix_product_variants_product', 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_tenant_id'), 'product_variants', ['tenant_id'], unique=False)
    op.create_index('uq_product_variants_tenant_barcode', 'product_variants', ['tenant_id', 'barcode'], unique=True)
    op.create_index('uq_product_variants_tenant_sku', 'product_variants', ['tenant_id', 'sku'], unique=True)
    op.create_table('purchases',
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('supplier_id', app.core.db.GUID(), nullable=True),
    sa.Column('branch_id', app.core.db.GUID(), nullable=False),
    sa.Column('location_id', app.core.db.GUID(), nullable=False),
    sa.Column('status', sa.Enum('received', 'cancelled', name='purchasestatus', native_enum=False, length=48), nullable=False),
    sa.Column('received_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('goods_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('transport_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('other_costs', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('cost_allocation_method', sa.String(length=24), nullable=False),
    sa.Column('supplier_invoice_ref', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.Column('created_by_id', app.core.db.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_purchases_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_purchases_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['stock_locations.id'], name=op.f('fk_purchases_location_id_stock_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchases_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_purchases_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchases')),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_purchases_tenant_idempotency'),
    sa.UniqueConstraint('tenant_id', 'number', name='uq_purchases_tenant_number')
    )
    op.create_index(op.f('ix_purchases_branch_id'), 'purchases', ['branch_id'], unique=False)
    op.create_index(op.f('ix_purchases_supplier_id'), 'purchases', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_purchases_tenant_id'), 'purchases', ['tenant_id'], unique=False)
    op.create_index('ix_purchases_tenant_received', 'purchases', ['tenant_id', 'received_at'], unique=False)
    op.create_table('sales',
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('branch_id', app.core.db.GUID(), nullable=False),
    sa.Column('location_id', app.core.db.GUID(), nullable=False),
    sa.Column('customer_id', app.core.db.GUID(), nullable=True),
    sa.Column('salesperson_id', app.core.db.GUID(), nullable=True),
    sa.Column('status', sa.Enum('completed', 'voided', name='salestatus', native_enum=False, length=48), nullable=False),
    sa.Column('sold_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.Column('voided_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('voided_by_id', app.core.db.GUID(), nullable=True),
    sa.Column('void_reason', sa.String(length=255), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.Column('created_by_id', app.core.db.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_sales_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_sales_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_sales_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['stock_locations.id'], name=op.f('fk_sales_location_id_stock_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salesperson_id'], ['users.id'], name=op.f('fk_sales_salesperson_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sales_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voided_by_id'], ['users.id'], name=op.f('fk_sales_voided_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales')),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_sales_tenant_idempotency'),
    sa.UniqueConstraint('tenant_id', 'number', name='uq_sales_tenant_number')
    )
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_salesperson_id'), 'sales', ['salesperson_id'], unique=False)
    op.create_index('ix_sales_tenant_branch', 'sales', ['tenant_id', 'branch_id'], unique=False)
    op.create_index(op.f('ix_sales_tenant_id'), 'sales', ['tenant_id'], unique=False)
    op.create_index('ix_sales_tenant_sold_at', 'sales', ['tenant_id', 'sold_at'], unique=False)
    op.create_table('stock_counts',
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('location_id', app.core.db.GUID(), nullable=False),
    sa.Column('branch_id', app.core.db.GUID(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'posted', 'cancelled', name='stockcountstatus', native_enum=False, length=48), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('posted_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('posted_by_id', app.core.db.GUID(), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.Column('created_by_id', app.core.db.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_stock_counts_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_stock_counts_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['stock_locations.id'], name=op.f('fk_stock_counts_location_id_stock_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], name=op.f('fk_stock_counts_posted_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_stock_counts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_counts')),
    sa.UniqueConstraint('tenant_id', 'reference', name='uq_stock_counts_tenant_reference')
    )
    op.create_index(op.f('ix_stock_counts_tenant_id'), 'stock_counts', ['tenant_id'], unique=False)
    op.create_table('stock_transfers',
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('from_location_id', app.core.db.GUID(), nullable=False),
    sa.Column('to_location_id', app.core.db.GUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'dispatched', 'received', 'cancelled', name='transferstatus', native_enum=False, length=48), nullable=False),
    sa.Column('dispatched_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('received_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('dispatched_by_id', app.core.db.GUID(), nullable=True),
    sa.Column('received_by_id', app.core.db.GUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.Column('created_by_id', app.core.db.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_stock_transfers_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dispatched_by_id'], ['users.id'], name=op.f('fk_stock_transfers_dispatched_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_location_id'], ['stock_locations.id'], name=op.f('fk_stock_transfers_from_location_id_stock_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], name=op.f('fk_stock_transfers_received_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_stock_transfers_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_location_id'], ['stock_locations.id'], name=op.f('fk_stock_transfers_to_location_id_stock_locations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_transfers')),
    sa.UniqueConstraint('tenant_id', 'reference', name='uq_stock_transfers_tenant_reference')
    )
    op.create_index(op.f('ix_stock_transfers_tenant_id'), 'stock_transfers', ['tenant_id'], unique=False)
    op.create_table('user_permission_grants',
    sa.Column('membership_id', app.core.db.GUID(), nullable=False),
    sa.Column('permission', sa.Enum('business:view', 'business:manage', 'branch:view', 'branch:manage', 'user:view', 'user:manage', 'settings:manage', 'audit:view', 'product:view', 'product:manage', 'product:import', 'cost:view', 'pricing:manage', 'stock:view', 'stock:receive', 'stock:transfer', 'stock:adjust', 'stock:count', 'sale:view', 'sale:create', 'sale:void', 'discount:approve', 'purchase:view', 'purchase:create', 'customer:view', 'customer:manage', 'supplier:view', 'supplier:manage', 'credit:view', 'credit:create', 'credit:payment', 'credit:duedate', 'credit:cancel', 'credit:limit_override', 'credit:followup', 'shop:view', 'shop:manage', 'enquiry:view', 'enquiry:manage', 'quotation:view', 'quotation:manage', 'report:sales', 'report:profit', 'report:inventory', 'report:credit', 'report:branch_compare', name='permission', native_enum=False, length=48), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['tenant_memberships.id'], name=op.f('fk_user_permission_grants_membership_id_tenant_memberships'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_permission_grants')),
    sa.UniqueConstraint('membership_id', 'permission', name='uq_user_permission_grants_membership_permission')
    )
    op.create_index(op.f('ix_user_permission_grants_membership_id'), 'user_permission_grants', ['membership_id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('receivable', 'payable', name='creditkind', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('outstanding', 'partially_paid', 'paid', 'overdue', 'cancelled', name='creditstatus', native_enum=False, length=48), nullable=False),
    sa.Column('branch_id', app.core.db.GUID(), nullable=True),
    sa.Column('customer_id', app.core.db.GUID(), nullable=True),
    sa.Column('supplier_id', app.core.db.GUID(), nullable=True),
    sa.Column('sale_id', app.core.db.GUID(), nullable=True),
    sa.Column('purchase_id', app.core.db.GUID(), nullable=True),
    sa.Column('original_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('agreement_note', sa.Text(), nullable=True),
    sa.Column('settled_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('cancelled_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('cancelled_by_id', app.core.db.GUID(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=255), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.Column('created_by_id', app.core.db.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_credit_transactions_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], name=op.f('fk_credit_transactions_cancelled_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_credit_transactions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_credit_transactions_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], name=op.f('fk_credit_transactions_purchase_id_purchases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('fk_credit_transactions_sale_id_sales'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_credit_transactions_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_credit_transactions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_transactions')),
    sa.UniqueConstraint('purchase_id', name=op.f('uq_credit_transactions_purchase_id')),
    sa.UniqueConstraint('sale_id', name=op.f('uq_credit_transactions_sale_id')),
    sa.UniqueConstraint('tenant_id', 'reference', name='uq_credit_transactions_tenant_reference')
    )
    op.create_index(op.f('ix_credit_transactions_branch_id'), 'credit_transactions', ['branch_id'], unique=False)
    op.create_index('ix_credit_transactions_customer', 'credit_transactions', ['customer_id'], unique=False)
    op.create_index('ix_credit_transactions_due_date', 'credit_transactions', ['tenant_id', 'due_date'], unique=False)
    op.create_index('ix_credit_transactions_supplier', 'credit_transactions', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_tenant_id'), 'credit_transactions', ['tenant_id'], unique=False)
    op.create_index('ix_credit_transactions_tenant_kind_status', 'credit_transactions', ['tenant_id', 'kind', 'status'], unique=False)
    op.create_table('purchase_lines',
    sa.Column('purchase_id', app.core.db.GUID(), nullable=False),
    sa.Column('product_id', app.core.db.GUID(), nullable=False),
    sa.Column('variant_id', app.core.db.GUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('allocated_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_purchase_lines_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], name=op.f('fk_purchase_lines_purchase_id_purchases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_purchase_lines_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_lines'))
    )
    op.create_index(op.f('ix_purchase_lines_product_id'), 'purchase_lines', ['product_id'], unique=False)
    op.create_index('ix_purchase_lines_purchase', 'purchase_lines', ['purchase_id'], unique=False)
    op.create_table('quotations',
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'accepted', 'declined', 'expired', 'converted', 'cancelled', name='quotationstatus', native_enum=False, length=48), nullable=False),
    sa.Column('branch_id', app.core.db.GUID(), nullable=True),
    sa.Column('customer_id', app.core.db.GUID(), nullable=True),
    sa.Column('enquiry_id', app.core.db.GUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('customer_phone', sa.String(length=32), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_company', sa.String(length=120), nullable=True),
    sa.Column('delivery_location', sa.String(length=255), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('delivery_charge', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('sent_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('accepted_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('declined_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('converted_sale_id', app.core.db.GUID(), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.Column('created_by_id', app.core.db.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_quotations_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['converted_sale_id'], ['sales.id'], name=op.f('fk_quotations_converted_sale_id_sales'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_quotations_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_quotations_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enquiry_id'], ['customer_enquiries.id'], name=op.f('fk_quotations_enquiry_id_customer_enquiries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_quotations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotations')),
    sa.UniqueConstraint('share_token', name='uq_quotations_share_token'),
    sa.UniqueConstraint('tenant_id', 'number', name='uq_quotations_tenant_number')
    )
    op.create_index(op.f('ix_quotations_share_token'), 'quotations', ['share_token'], unique=False)
    op.create_index(op.f('ix_quotations_tenant_id'), 'quotations', ['tenant_id'], unique=False)
    op.create_index('ix_quotations_tenant_status', 'quotations', ['tenant_id', 'status'], unique=False)
    op.create_table('sale_lines',
    sa.Column('sale_id', app.core.db.GUID(), nullable=False),
    sa.Column('product_id', app.core.db.GUID(), nullable=False),
    sa.Column('variant_id', app.core.db.GUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('discount_approved_by_id', app.core.db.GUID(), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['discount_approved_by_id'], ['users.id'], name=op.f('fk_sale_lines_discount_approved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sale_lines_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('fk_sale_lines_sale_id_sales'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_sale_lines_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale_lines'))
    )
    op.create_index(op.f('ix_sale_lines_product_id'), 'sale_lines', ['product_id'], unique=False)
    op.create_index('ix_sale_lines_sale', 'sale_lines', ['sale_id'], unique=False)
    op.create_table('stock_balances',
    sa.Column('product_id', app.core.db.GUID(), nullable=False),
    sa.Column('variant_id', app.core.db.GUID(), nullable=False),
    sa.Column('location_id', app.core.db.GUID(), nullable=False),
    sa.Column('branch_id', app.core.db.GUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_stock_balances_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['stock_locations.id'], name=op.f('fk_stock_balances_location_id_stock_locations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_balances_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_stock_balances_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_stock_balances_variant_id_product_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_balances')),
    sa.UniqueConstraint('tenant_id', 'variant_id', 'location_id', name='uq_stock_balances_variant_location')
    )
    op.create_index(op.f('ix_stock_balances_product_id'), 'stock_balances', ['product_id'], unique=False)
    op.create_index('ix_stock_balances_tenant_branch', 'stock_balances', ['tenant_id', 'branch_id'], unique=False)
    op.create_index(op.f('ix_stock_balances_tenant_id'), 'stock_balances', ['tenant_id'], unique=False)
    op.create_table('stock_count_lines',
    sa.Column('count_id', app.core.db.GUID(), nullable=False),
    sa.Column('product_id', app.core.db.GUID(), nullable=False),
    sa.Column('variant_id', app.core.db.GUID(), nullable=False),
    sa.Column('expected_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('counted_quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('counted_by_id', app.core.db.GUID(), nullable=True),
    sa.Column('counted_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['count_id'], ['stock_counts.id'], name=op.f('fk_stock_count_lines_count_id_stock_counts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['counted_by_id'], ['users.id'], name=op.f('fk_stock_count_lines_counted_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_count_lines_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_stock_count_lines_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_count_lines')),
    sa.UniqueConstraint('count_id', 'variant_id', name='uq_stock_count_lines_count_variant')
    )
    op.create_index(op.f('ix_stock_count_lines_count_id'), 'stock_count_lines', ['count_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('product_id', app.core.db.GUID(), nullable=False),
    sa.Column('variant_id', app.core.db.GUID(), nullable=False),
    sa.Column('location_id', app.core.db.GUID(), nullable=False),
    sa.Column('branch_id', app.core.db.GUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reason', sa.Enum('opening', 'purchase', 'sale', 'sale_return', 'purchase_return', 'transfer_out', 'transfer_in', 'adjustment', 'count_adjustment', 'damage', 'loss', 'sale_void', name='movementreason', native_enum=False, length=48), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('source_id', app.core.db.GUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.Column('created_by_id', app.core.db.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_stock_movements_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_stock_movements_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['stock_locations.id'], name=op.f('fk_stock_movements_location_id_stock_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_movements_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_stock_movements_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_stock_movements_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements')),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_stock_movements_tenant_idempotency')
    )
    op.create_index(op.f('ix_stock_movements_branch_id'), 'stock_movements', ['branch_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_product_id'), 'stock_movements', ['product_id'], unique=False)
    op.create_index('ix_stock_movements_source', 'stock_movements', ['source_type', 'source_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_tenant_id'), 'stock_movements', ['tenant_id'], unique=False)
    op.create_index('ix_stock_movements_tenant_occurred', 'stock_movements', ['tenant_id', 'occurred_at'], unique=False)
    op.create_index('ix_stock_movements_variant_location', 'stock_movements', ['variant_id', 'location_id'], unique=False)
    op.create_table('stock_transfer_lines',
    sa.Column('transfer_id', app.core.db.GUID(), nullable=False),
    sa.Column('product_id', app.core.db.GUID(), nullable=False),
    sa.Column('variant_id', app.core.db.GUID(), nullable=False),
    sa.Column('quantity_sent', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_transfer_lines_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], name=op.f('fk_stock_transfer_lines_transfer_id_stock_transfers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_stock_transfer_lines_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_transfer_lines'))
    )
    op.create_index(op.f('ix_stock_transfer_lines_transfer_id'), 'stock_transfer_lines', ['transfer_id'], unique=False)
    op.create_table('follow_up_activities',
    sa.Column('credit_transaction_id', app.core.db.GUID(), nullable=False),
    sa.Column('kind', sa.Enum('called', 'message_sent', 'promise_to_pay', 'arrangement', 'note', name='followupkind', native_enum=False, length=48), nullable=False),
    sa.Column('occurred_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('promised_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('promised_date', sa.Date(), nullable=True),
    sa.Column('outcome', sa.String(length=120), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.Column('created_by_id', app.core.db.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_follow_up_activities_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['credit_transaction_id'], ['credit_transactions.id'], name=op.f('fk_follow_up_activities_credit_transaction_id_credit_transactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_follow_up_activities_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follow_up_activities'))
    )
    op.create_index(op.f('ix_follow_up_activities_credit_transaction_id'), 'follow_up_activities', ['credit_transaction_id'], unique=False)
    op.create_index(op.f('ix_follow_up_activities_tenant_id'), 'follow_up_activities', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('direction', sa.Enum('in', 'out', name='paymentdirection', native_enum=False, length=48), nullable=False),
    sa.Column('method', sa.Enum('cash', 'bank_transfer', 'telebirr', 'cbe_birr', 'mobile_money', 'card', 'cheque', 'other', name='paymentmethod', native_enum=False, length=48), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('paid_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('branch_id', app.core.db.GUID(), nullable=True),
    sa.Column('sale_id', app.core.db.GUID(), nullable=True),
    sa.Column('purchase_id', app.core.db.GUID(), nullable=True),
    sa.Column('credit_transaction_id', app.core.db.GUID(), nullable=True),
    sa.Column('customer_id', app.core.db.GUID(), nullable=True),
    sa.Column('supplier_id', app.core.db.GUID(), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=False),
    sa.Column('reversed_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('reversed_by_id', app.core.db.GUID(), nullable=True),
    sa.Column('reversal_reason', sa.String(length=255), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.Column('created_by_id', app.core.db.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_payments_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_payments_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['credit_transaction_id'], ['credit_transactions.id'], name=op.f('fk_payments_credit_transaction_id_credit_transactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_payments_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], name=op.f('fk_payments_purchase_id_purchases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reversed_by_id'], ['users.id'], name=op.f('fk_payments_reversed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('fk_payments_sale_id_sales'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_payments_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_payments_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_payments_tenant_idempotency')
    )
    op.create_index(op.f('ix_payments_branch_id'), 'payments', ['branch_id'], unique=False)
    op.create_index('ix_payments_credit_transaction', 'payments', ['credit_transaction_id'], unique=False)
    op.create_index(op.f('ix_payments_purchase_id'), 'payments', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_payments_sale_id'), 'payments', ['sale_id'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_index('ix_payments_tenant_paid_at', 'payments', ['tenant_id', 'paid_at'], unique=False)
    op.create_table('quotation_lines',
    sa.Column('quotation_id', app.core.db.GUID(), nullable=False),
    sa.Column('product_id', app.core.db.GUID(), nullable=True),
    sa.Column('variant_id', app.core.db.GUID(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_quotation_lines_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_quotation_lines_quotation_id_quotations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_quotation_lines_variant_id_product_variants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_lines'))
    )
    op.create_index('ix_quotation_lines_quotation', 'quotation_lines', ['quotation_id'], unique=False)
    op.create_table('reminders',
    sa.Column('credit_transaction_id', app.core.db.GUID(), nullable=False),
    sa.Column('kind', sa.Enum('due_soon', 'due_today', 'overdue', name='reminderkind', native_enum=False, length=48), nullable=False),
    sa.Column('channel', sa.Enum('in_app', 'email', 'push', name='reminderchannel', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'sent', 'failed', 'cancelled', name='reminderstatus', native_enum=False, length=48), nullable=False),
    sa.Column('scheduled_for', sa.Date(), nullable=False),
    sa.Column('sent_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('tenant_id', app.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['credit_transaction_id'], ['credit_transactions.id'], name=op.f('fk_reminders_credit_transaction_id_credit_transactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_reminders_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders')),
    sa.UniqueConstraint('credit_transaction_id', 'kind', 'channel', 'scheduled_for', name='uq_reminders_transaction_kind_channel_date')
    )
    op.create_index(op.f('ix_reminders_credit_transaction_id'), 'reminders', ['credit_transaction_id'], unique=False)
    op.create_index(op.f('ix_reminders_tenant_id'), 'reminders', ['tenant_id'], unique=False)
    op.create_index('ix_reminders_tenant_scheduled', 'reminders', ['tenant_id', 'scheduled_for', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reminders_tenant_scheduled', table_name='reminders')
    op.drop_index(op.f('ix_reminders_tenant_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_credit_transaction_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index('ix_quotation_lines_quotation', table_name='quotation_lines')
    op.drop_table('quotation_lines')
    op.drop_index('ix_payments_tenant_paid_at', table_name='payments')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_sale_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_purchase_id'), table_name='payments')
    op.drop_index('ix_payments_credit_transaction', table_name='payments')
    op.drop_index(op.f('ix_payments_branch_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_follow_up_activities_tenant_id'), table_name='follow_up_activities')
    op.drop_index(op.f('ix_follow_up_activities_credit_transaction_id'), table_name='follow_up_activities')
    op.drop_table('follow_up_activities')
    op.drop_index(op.f('ix_stock_transfer_lines_transfer_id'), table_name='stock_transfer_lines')
    op.drop_table('stock_transfer_lines')
    op.drop_index('ix_stock_movements_variant_location', table_name='stock_movements')
    op.drop_index('ix_stock_movements_tenant_occurred', table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_tenant_id'), table_name='stock_movements')
    op.drop_index('ix_stock_movements_source', table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_product_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_branch_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_stock_count_lines_count_id'), table_name='stock_count_lines')
    op.drop_table('stock_count_lines')
    op.drop_index(op.f('ix_stock_balances_tenant_id'), table_name='stock_balances')
    op.drop_index('ix_stock_balances_tenant_branch', table_name='stock_balances')
    op.drop_index(op.f('ix_stock_balances_product_id'), table_name='stock_balances')
    op.drop_table('stock_balances')
    op.drop_index('ix_sale_lines_sale', table_name='sale_lines')
    op.drop_index(op.f('ix_sale_lines_product_id'), table_name='sale_lines')
    op.drop_table('sale_lines')
    op.drop_index('ix_quotations_tenant_status', table_name='quotations')
    op.drop_index(op.f('ix_quotations_tenant_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_share_token'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index('ix_purchase_lines_purchase', table_name='purchase_lines')
    op.drop_index(op.f('ix_purchase_lines_product_id'), table_name='purchase_lines')
    op.drop_table('purchase_lines')
    op.drop_index('ix_credit_transactions_tenant_kind_status', table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_tenant_id'), table_name='credit_transactions')
    op.drop_index('ix_credit_transactions_supplier', table_name='credit_transactions')
    op.drop_index('ix_credit_transactions_due_date', table_name='credit_transactions')
    op.drop_index('ix_credit_transactions_customer', table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_branch_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_user_permission_grants_membership_id'), table_name='user_permission_grants')
    op.drop_table('user_permission_grants')
    op.drop_index(op.f('ix_stock_transfers_tenant_id'), table_name='stock_transfers')
    op.drop_table('stock_transfers')
    op.drop_index(op.f('ix_stock_counts_tenant_id'), table_name='stock_counts')
    op.drop_table('stock_counts')
    op.drop_index('ix_sales_tenant_sold_at', table_name='sales')
    op.drop_index(op.f('ix_sales_tenant_id'), table_name='sales')
    op.drop_index('ix_sales_tenant_branch', table_name='sales')
    op.drop_index(op.f('ix_sales_salesperson_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index('ix_purchases_tenant_received', table_name='purchases')
    op.drop_index(op.f('ix_purchases_tenant_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_supplier_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_branch_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index('uq_product_variants_tenant_sku', table_name='product_variants')
    op.drop_index('uq_product_variants_tenant_barcode', table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_tenant_id'), table_name='product_variants')
    op.drop_index('ix_product_variants_product', table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index('ix_pricing_rules_tenant_scope', table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_tenant_id'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_index(op.f('ix_import_row_errors_job_id'), table_name='import_row_errors')
    op.drop_table('import_row_errors')
    op.drop_index('ix_customer_enquiries_tenant_status', table_name='customer_enquiries')
    op.drop_index(op.f('ix_customer_enquiries_tenant_id'), table_name='customer_enquiries')
    op.drop_table('customer_enquiries')
    op.drop_index(op.f('ix_branch_assignments_membership_id'), table_name='branch_assignments')
    op.drop_index(op.f('ix_branch_assignments_branch_id'), table_name='branch_assignments')
    op.drop_table('branch_assignments')
    op.drop_index(op.f('ix_tenant_memberships_user_id'), table_name='tenant_memberships')
    op.drop_index(op.f('ix_tenant_memberships_tenant_id'), table_name='tenant_memberships')
    op.drop_index(op.f('ix_tenant_memberships_invitation_token'), table_name='tenant_memberships')
    op.drop_table('tenant_memberships')
    op.drop_index(op.f('ix_stock_locations_tenant_id'), table_name='stock_locations')
    op.drop_index(op.f('ix_stock_locations_branch_id'), table_name='stock_locations')
    op.drop_table('stock_locations')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('uq_products_tenant_sku', table_name='products')
    op.drop_index('ix_products_tenant_name', table_name='products')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index(op.f('ix_products_is_published'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_import_jobs_tenant_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index('ix_customers_tenant_phone', table_name='customers')
    op.drop_index('ix_customers_tenant_name', table_name='customers')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index('ix_suppliers_tenant_name', table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_tenant_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_online_stores_tenant_id'), table_name='online_stores')
    op.drop_table('online_stores')
    op.drop_index('ix_notifications_tenant_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_file_assets_tenant_id'), table_name='file_assets')
    op.drop_table('file_assets')
    op.drop_index(op.f('ix_feature_flags_tenant_id'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_categories_tenant_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_branches_tenant_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_table('subscription_plans')
    op.drop_table('platform_admins')
    # ### end Alembic commands ###
